name: example
description: A sample command-line application.

environment:
  sdk: ^3.4.0-4.0.dev

# Add regular dependencies here.
dependencies:
  intl:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
